homeassistant:
  name: Home
  latitude: 47.2945
  longitude: -122.622
  elevation: 63
  unit_system: imperial
  time_zone: America/Los_Angeles
  customize: !include customize.yaml
  customize_domain:
    light:
      polling_intensity: 2
    switch:
      polling_intensity: 1

zwave:
  autoheal: false
  network_key: !secret zwave_network_key
  polling_interval: 30000
  usb_path: /dev/ttyUSB0

zha:
  usb_path: /dev/ttyUSB1
  database_path: zigbee.db

#introduction:

frontend:

config:

system_health:

http:
  api_password: !secret http_password
  base_url: http://192.168.86.208:8123
  server_port: !secret server_port
  # ssl_certificate: !secret ssl_certificate
  # ssl_key: !secret ssl_key

updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

discovery:
conversation:
history:
logbook:
map:
sun:
sensor:
  - platform: yr
tts:
  - platform: google_translate
  
frontend:
  themes: !include_dir_merge_named themes

group: !include_dir_named groups
automation: !include_dir_merge_list automations
script: !include scripts.yaml
scene: !include_dir_list scenes

input_boolean: !include input_boolean.yaml

wemo:
  static:
    - 192.168.86.160
    - 192.168.86.161
    - 192.168.86.162
    - 192.168.86.163
    - 192.168.86.164
    - 192.168.86.165

media_player:
  - platform: samsungtv
    host: 192.168.86.187
    port: 8001
    mac: 28:39:5E:97:04:C7
    name: Samsung TV

logger:
  default: critical
